# Generated by Django 2.0.5 on 2018-06-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='response',
            field=models.TextField(default='No take.'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='batch',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.College'),
        ),
    ]
