# Generated by Django 2.0.5 on 2018-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20180618_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_id_number',
            field=models.TextField(unique=True),
        ),
    ]
