# Generated by Django 2.0.5 on 2018-06-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20180622_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='batch',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.College'),
        ),
    ]
