# Generated by Django 2.0.5 on 2018-06-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20180622_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
