# Generated by Django 2.0.5 on 2018-07-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20180701_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='party',
        ),
    ]
