# Generated by Django 2.0.5 on 2018-07-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0014_auto_20180701_2012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('position', 'party')},
        ),
    ]
