# Generated by Django 2.0.5 on 2018-08-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0015_auto_20180708_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=4)),
                ('college', models.ManyToManyField(to='vote.College')),
            ],
        ),
    ]
