# Generated by Django 2.0.5 on 2018-08-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0016_electionstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionstatus',
            name='college',
        ),
    ]
