# Generated by Django 2.0.5 on 2018-08-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0017_remove_electionstatus_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionstatus',
            name='college',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.College'),
        ),
    ]
