# Generated by Django 2.0.5 on 2018-08-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0020_auto_20180831_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionstatus',
            name='college',
        ),
        migrations.DeleteModel(
            name='ElectionStatus',
        ),
    ]
