# Generated by Django 2.0.5 on 2018-08-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0021_auto_20180831_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=4)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.College')),
            ],
        ),
    ]
