# Generated by Django 2.0.5 on 2018-09-09 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0023_auto_20180909_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
