# Generated by Django 2.0.5 on 2018-09-09 16:08

from django.db import migrations, models
import django.db.models.deletion
import vote.models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0024_auto_20180909_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('EX', 'Executive'), ('BT', 'Batch'), (vote.models.College, 'College')], max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='base_position',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='vote.BasePosition'),
            preserve_default=False,
        ),
    ]
