# Generated by Django 2.0.5 on 2018-09-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0026_auto_20180910_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseposition',
            name='type',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Batch', 'Batch'), ('College', 'College')], max_length=16),
        ),
    ]
