# Generated by Django 2.0.5 on 2018-09-10 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0027_auto_20180910_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteset',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.Candidate'),
        ),
    ]
