# Generated by Django 2.0.5 on 2018-09-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0028_auto_20180910_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='currently_voting',
            field=models.BooleanField(default=False),
        ),
    ]
