# Generated by Django 2.0.5 on 2018-09-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0029_voter_currently_voting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='currently_voting',
        ),
    ]
