# Generated by Django 2.0.5 on 2018-09-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0032_position_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='new',
        ),
    ]
