# Generated by Django 2.0.5 on 2018-09-15 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0033_remove_position_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
