# Generated by Django 2.0.5 on 2018-09-15 01:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0034_position_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
