# Generated by Django 2.0.5 on 2018-09-16 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0035_auto_20180915_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
