# Generated by Django 3.0.3 on 2020-03-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0036_auto_20180916_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='priority',
            field=models.IntegerField(default=100),
        ),
    ]
