# Generated by Django 3.0.3 on 2020-03-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0038_auto_20200312_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['position__priority']},
        ),
    ]
