# Generated by Django 3.0.3 on 2020-06-16 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0040_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('YES', 'yes'), ('NO', 'no'), ('ABSTAIN', 'abstain')], max_length=7)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote.Poll')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Vote')),
            ],
        ),
    ]
