# Generated by Django 3.0.3 on 2020-06-17 00:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0041_pollset'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
