# Generated by Django 3.1.2 on 2020-11-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0042_poll_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ONGOING', 'Ongoing'), ('PAUSED', 'Paused'), ('BLOCKED', 'Blocking Results'), ('FINISHED', 'Finished'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
