# Generated by Django 3.1.2 on 2020-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0043_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='state',
            field=models.CharField(choices=[('ONGOING', 'ongoing'), ('PAUSED', 'paused'), ('BLOCKED', 'blocked'), ('FINISHED', 'finished'), ('ARCHIVED', 'archived')], max_length=20),
        ),
    ]
